import React,{useEffect,useRef,useState} from 'react';
const W=540,H=960,DAILY=20,BOSS=10,CRYSTAL_TARGET=1000,CRYSTAL_REWARD=5;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const day=()=>new Date().toISOString().slice(0,10);
const loadDaily=()=>{try{const x=JSON.parse(localStorage.getItem('spnxDaily')||'{}');return x.date===day()?x:{date:day(),earned:0}}catch{return{date:day(),earned:0}}};
export default function Game(){
 const ref=useRef(null); const [mode,setMode]=useState('ready'); const [run,setRun]=useState(0); const [guide,setGuide]=useState(false); const [daily,setDaily]=useState(loadDaily()); const [hud,setHud]=useState({score:0,hp:100,stage:1,crystals:Number(localStorage.getItem('spnxCrystals')||0),boss:0}); const [msg,setMsg]=useState('Captain, prepare NOVA-X1.');
 const reward=(type,amt)=>setDaily(p=>{const cur=p.date===day()?p:{date:day(),earned:0},g=Math.min(amt,Math.max(0,DAILY-cur.earned)),n={date:day(),earned:cur.earned+g};localStorage.setItem('spnxDaily',JSON.stringify(n));setMsg(g?`${type} +${g} SPNX`:'Daily 20 SPNX complete');return n});
 useEffect(()=>{if(mode!=='playing')return;const c=ref.current,ctx=c.getContext('2d');let stop=false,raf,last=performance.now(),spawn=0,bossT=0,hudT=0,drag=false;const keys=new Set();const s={score:0,hp:100,stage:1,crystals:Number(localStorage.getItem('spnxCrystals')||0),ship:{x:W/2,y:H-120,tx:W/2,power:1,shield:0,tilt:0},bul:[],en:[],eb:[],drops:[],parts:[],stars:[],boss:null,lastShot:0,dead:false};for(let i=0;i<150;i++)s.stars.push({x:Math.random()*W,y:Math.random()*H,v:40+Math.random()*120,z:.5+Math.random()*2});
 const burst=(x,y,col,n=20)=>{for(let i=0;i<n;i++){const a=Math.random()*6.28,v=50+Math.random()*260;s.parts.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,l:.4+Math.random()*.7,c:col,r:2+Math.random()*4})}};
 const shot=()=>{const now=performance.now();if(now-s.lastShot<(s.ship.power>1?95:150))return;s.lastShot=now;(s.ship.power>=3?[-20,0,20]:s.ship.power===2?[-13,13]:[0]).forEach(dx=>s.bul.push({x:s.ship.x+dx,y:s.ship.y-50,vx:dx*.7,vy:-720,d:s.ship.power>=3?2:1}))};
 const formation=()=>{const n=5+Math.min(4,s.stage);for(let i=0;i<n;i++){const elite=i%4===0&&s.stage>1,x=W/2+(i-(n-1)/2)*58;s.en.push({x,y:-70-Math.abs(i-(n-1)/2)*30,bx:x,hp:elite?5:2,size:elite?30:23,v:90+s.stage*13+Math.random()*35,p:Math.random()*6.28,t:elite?'elite':'fighter',shot:1+Math.random()*2})}};
 const boss=()=>{s.boss={x:W/2,y:-150,hp:160+s.stage*45,max:160+s.stage*45,p:0,shot:.6};setMsg('WARNING · ENEMY FLAGSHIP');navigator.vibrate?.([120,60,120])};
 const coll=(a,b,r)=>Math.hypot(a.x-b.x,a.y-b.y)<r;
 const drop=(x,y)=>{const r=Math.random(),t=r<.68?'crystal':r<.82?'power':r<.92?'shield':'heal';s.drops.push({x,y,t,v:120,rot:0})};
 const finish=()=>{if(s.dead)return;s.dead=true;burst(s.ship.x,s.ship.y,'#ff4e73',90);setTimeout(()=>{if(!stop)setMode('gameover')},650)};
 const update=dt=>{s.stage=1+Math.floor(s.score/1200);s.ship.shield=Math.max(0,s.ship.shield-dt);let d=0;if(keys.has('ArrowLeft')||keys.has('KeyA'))d--;if(keys.has('ArrowRight')||keys.has('KeyD'))d++;s.ship.tx=clamp(s.ship.tx+d*360*dt,42,W-42);s.ship.x+=(s.ship.tx-s.ship.x)*Math.min(1,dt*13);s.ship.tilt+=(d*.22-s.ship.tilt)*Math.min(1,dt*9);shot();s.stars.forEach(x=>{x.y+=x.v*dt;if(x.y>H){x.y=-5;x.x=Math.random()*W}});s.bul.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt});s.bul=s.bul.filter(b=>b.y>-50);spawn-=dt;if(!s.boss&&spawn<=0){formation();spawn=Math.max(1,2.2-s.stage*.1)}bossT+=dt;if(!s.boss&&bossT>34){boss();bossT=0}s.en.forEach(e=>{e.y+=e.v*dt;e.x=e.bx+Math.sin(e.y*.013+e.p)*55;e.shot-=dt;if(e.shot<=0&&e.y>60&&e.y<620){const a=Math.atan2(s.ship.y-e.y,s.ship.x-e.x);s.eb.push({x:e.x,y:e.y,vx:Math.cos(a)*190,vy:Math.sin(a)*190,r:5});e.shot=1.6+Math.random()*1.6}});if(s.boss){let b=s.boss;b.p+=dt;if(b.y<165)b.y+=100*dt;else b.x=W/2+Math.sin(b.p*.8)*150;b.shot-=dt;if(b.shot<=0){for(let i=-2;i<=2;i++)s.eb.push({x:b.x,y:b.y+55,vx:Math.cos(Math.PI/2+i*.18)*220,vy:Math.sin(Math.PI/2+i*.18)*220,r:6});b.shot=.75}}
 for(let bi=s.bul.length-1;bi>=0;bi--){let used=false,b=s.bul[bi];for(let ei=s.en.length-1;ei>=0;ei--){let e=s.en[ei];if(coll(b,e,e.size+7)){e.hp-=b.d;s.bul.splice(bi,1);used=true;if(e.hp<=0){s.score+=e.t==='elite'?30:10;burst(e.x,e.y,e.t==='elite'?'#ff5ad8':'#52eaff',e.t==='elite'?30:18);if(Math.random()<.55)drop(e.x,e.y);s.en.splice(ei,1)}break}}if(!used&&s.boss&&coll(b,s.boss,73)){s.boss.hp-=b.d;s.bul.splice(bi,1);if(s.boss.hp<=0){burst(s.boss.x,s.boss.y,'#ffd76b',120);s.boss=null;s.score+=500;reward('BOSS DESTROYED',BOSS);navigator.vibrate?.([100,40,100,40,180])}}}
 for(let i=s.en.length-1;i>=0;i--){let e=s.en[i];if(coll(s.ship,e,e.size+28)){s.en.splice(i,1);burst(e.x,e.y,'#ff5f79',28);if(s.ship.shield>0)s.ship.shield=0;else s.hp-=e.t==='elite'?28:18}else if(e.y>H+60)s.en.splice(i,1)}for(let i=s.eb.length-1;i>=0;i--){let b=s.eb[i];b.x+=b.vx*dt;b.y+=b.vy*dt;if(coll(s.ship,b,25)){s.eb.splice(i,1);if(s.ship.shield>0)s.ship.shield=0;else s.hp-=8}else if(b.y>H+30||b.x<-30||b.x>W+30)s.eb.splice(i,1)}s.drops.forEach(x=>{x.y+=x.v*dt;x.rot+=dt*3});for(let i=s.drops.length-1;i>=0;i--){let x=s.drops[i];if(coll(s.ship,x,34)){if(x.t==='crystal'){s.crystals++;localStorage.setItem('spnxCrystals',s.crystals);if(s.crystals%CRYSTAL_TARGET===0)reward('1000 CRYSTALS',CRYSTAL_REWARD)}if(x.t==='power')s.ship.power=Math.min(3,s.ship.power+1);if(x.t==='shield')s.ship.shield=12;if(x.t==='heal')s.hp=Math.min(100,s.hp+25);burst(x.x,x.y,x.t==='crystal'?'#4ceeff':'#ffd86b',16);s.drops.splice(i,1)}else if(x.y>H+30)s.drops.splice(i,1)}s.parts.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.985;p.vy*=.985;p.l-=dt});s.parts=s.parts.filter(p=>p.l>0);hudT+=dt;if(hudT>.12){setHud({score:Math.floor(s.score),hp:Math.max(0,Math.floor(s.hp)),stage:s.stage,crystals:s.crystals,boss:s.boss?Math.max(0,s.boss.hp/s.boss.max*100):0});hudT=0}if(s.hp<=0)finish()};
 const ship=()=>{let p=s.ship;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.tilt);if(p.shield>0){ctx.strokeStyle='#4cf1ff';ctx.lineWidth=4;ctx.shadowColor='#4cf1ff';ctx.shadowBlur=20;ctx.beginPath();ctx.ellipse(0,0,53,67,0,0,6.28);ctx.stroke()}let g=ctx.createLinearGradient(-40,-60,40,50);g.addColorStop(0,'#fff');g.addColorStop(.35,'#8edcff');g.addColorStop(.7,'#304d84');g.addColorStop(1,'#dffaff');ctx.fillStyle=g;ctx.shadowColor='#52e8ff';ctx.shadowBlur=22;ctx.beginPath();ctx.moveTo(0,-64);ctx.lineTo(24,-25);ctx.lineTo(58,24);ctx.lineTo(21,13);ctx.lineTo(12,51);ctx.lineTo(0,34);ctx.lineTo(-12,51);ctx.lineTo(-21,13);ctx.lineTo(-58,24);ctx.lineTo(-24,-25);ctx.closePath();ctx.fill();ctx.fillStyle='#07142d';ctx.beginPath();ctx.ellipse(0,-20,11,24,0,0,6.28);ctx.fill();ctx.fillStyle='#52efff';ctx.beginPath();ctx.arc(0,9,7,0,6.28);ctx.fill();ctx.fillStyle='#74eaff';ctx.beginPath();ctx.moveTo(-9,42);ctx.lineTo(0,82+Math.random()*8);ctx.lineTo(9,42);ctx.fill();ctx.restore()};
 const draw=()=>{let bg=ctx.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#111a4f');bg.addColorStop(.45,'#050a24');bg.addColorStop(1,'#01030d');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);s.stars.forEach(x=>{ctx.fillStyle='#dff9ff';ctx.globalAlpha=.4;ctx.fillRect(x.x,x.y,x.z,x.z*2)});ctx.globalAlpha=1;s.drops.forEach(x=>{ctx.save();ctx.translate(x.x,x.y);ctx.rotate(x.rot);ctx.fillStyle=x.t==='crystal'?'#50eaff':x.t==='shield'?'#71f7ff':x.t==='heal'?'#68ff9a':'#ffd76b';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=18;ctx.beginPath();ctx.arc(0,0,13,0,6.28);ctx.fill();ctx.restore()});s.bul.forEach(b=>{ctx.fillStyle='#d8ffff';ctx.shadowColor='#52eaff';ctx.shadowBlur=12;ctx.fillRect(b.x-2,b.y-14,4,20)});s.eb.forEach(b=>{ctx.fillStyle='#ff739e';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,6.28);ctx.fill()});s.en.forEach(e=>{ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle=e.t==='elite'?'#a82a9a':'#922447';ctx.shadowColor=e.t==='elite'?'#ff55d7':'#ff506f';ctx.shadowBlur=18;ctx.beginPath();ctx.moveTo(0,31);ctx.lineTo(34,-22);ctx.lineTo(12,-13);ctx.lineTo(0,-34);ctx.lineTo(-12,-13);ctx.lineTo(-34,-22);ctx.closePath();ctx.fill();ctx.restore()});if(s.boss){let b=s.boss;ctx.save();ctx.translate(b.x,b.y);ctx.fillStyle='#6d164e';ctx.shadowColor='#ff5d8f';ctx.shadowBlur=30;ctx.beginPath();ctx.moveTo(0,-75);ctx.lineTo(105,-15);ctx.lineTo(82,66);ctx.lineTo(24,48);ctx.lineTo(0,82);ctx.lineTo(-24,48);ctx.lineTo(-82,66);ctx.lineTo(-105,-15);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle='rgba(255,255,255,.15)';ctx.fillRect(56,126,W-112,12);ctx.fillStyle='#ff4f85';ctx.fillRect(56,126,(W-112)*Math.max(0,b.hp/b.max),12)}s.parts.forEach(p=>{ctx.globalAlpha=Math.max(0,p.l);ctx.fillStyle=p.c;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,6.28);ctx.fill()});ctx.globalAlpha=1;if(!s.dead)ship()};
 const loop=now=>{if(stop)return;const dt=Math.min(.033,(now-last)/1000||0);last=now;if(!s.dead)update(dt);draw();raf=requestAnimationFrame(loop)};const pos=e=>{const r=c.getBoundingClientRect();s.ship.tx=clamp((e.clientX-r.left)/r.width*W,42,W-42)};const down=e=>{drag=true;pos(e)};const move=e=>{if(drag){e.preventDefault();pos(e)}};const up=()=>drag=false;const kd=e=>keys.add(e.code),ku=e=>keys.delete(e.code);c.addEventListener('pointerdown',down);c.addEventListener('pointermove',move);window.addEventListener('pointerup',up);window.addEventListener('keydown',kd);window.addEventListener('keyup',ku);raf=requestAnimationFrame(loop);return()=>{stop=true;cancelAnimationFrame(raf);c.removeEventListener('pointerdown',down);c.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('keydown',kd);window.removeEventListener('keyup',ku)}} , [mode,run]);
 return <section className="shell"><header><div><small>SPACENOVAX ARCADE</small><h1>NOVA-X1 Galaxy War</h1><p>{msg}</p></div><button onClick={()=>setGuide(true)}>GAME GUIDE</button></header><div className="rewards"><div>Today<b>{daily.earned}/20</b></div><div>Boss<b>+10 SPNX</b></div><div>1000 Crystals<b>+5 SPNX</b></div></div><div className="game"><canvas ref={ref} width={W} height={H}/><div className="hud"><span>SCORE {hud.score}</span><span>HP {hud.hp}</span><span>STAGE {hud.stage}</span></div><div className="bottom">💎 {hud.crystals} · NOVA-X1</div>{mode!=='playing'&&<div className="overlay"><div className="panel"><small>{mode==='gameover'?'MISSION FAILED':'FLEET COMMAND'}</small><h2>{mode==='gameover'?'NOVA-X1 DESTROYED':'DEFEND THE GALAXY'}</h2><p>Destroy enemy formations, collect crystals and defeat the enemy flagship.</p><button onClick={()=>{setMode('playing');setRun(x=>x+1)}}>{mode==='gameover'?'RETRY MISSION':'LAUNCH NOVA-X1'}</button></div></div>}</div>{guide&&<div className="modal" onClick={()=>setGuide(false)}><div className="guide" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setGuide(false)}>×</button><h2>GAME GUIDE</h2><p>👑 Boss defeated: <b>+10 SPNX</b></p><p>💎 1,000 crystals: <b>+5 SPNX</b></p><p>🎁 Daily game limit: <b>20 SPNX</b></p><p>Mobile: drag NOVA-X1 to move. Weapons fire automatically.</p></div></div>}</section>
}
